export const knownOperators = new Set([
  // Arithmetic & Math
  "abs",
  "add",
  "and",
  "atan",
  "ceiling",
  "cos",
  "cvi",
  "cvlit",
  "cvn",
  "cvr",
  "div",
  "exp",
  "floor",
  "idiv",
  "ln",
  "log",
  "mod",
  "mul",
  "neg",
  "not",
  "or",
  "round",
  "sin",
  "sqrt",
  "sub",
  "truncate",
  "xor",
  "rand",
  "rrand",
  "srand",

  // Stack manipulation
  "copy",
  "count",
  "counttomark",
  "cleartomark",
  "dup",
  "exch",
  "index",
  "pop",
  "roll",
  "clear",
  "mark",

  // Control & Execution
  "exec",
  "if",
  "ifelse",
  "for",
  "repeat",
  "loop",
  "exit",
  "stop",
  "stopped",
  "quit",
  "start",
  "forall",
  "bind",
  "load",
  "cvx",

  // Arrays
  "array",
  "length",
  "get",
  "put",
  "getinterval",
  "putinterval",
  "astore",
  "aload",

  // Dictionaries
  "dict",
  "maxlength",
  "begin",
  "end",
  "def",
  "store",
  "load",
  "where",
  "known",
  "undef",
  "systemdict",
  "userdict",
  "currentdict",

  // Strings
  "string",
  "length",
  "get",
  "put",
  "getinterval",
  "putinterval",
  "anchorsearch",
  "search",
  "token",
  "cvs",
  "cvrs",

  // Files & IO
  "file",
  "closefile",
  "deletefile",
  "renamefile",
  "status",
  "currentfile",
  "print",
  "write",
  "writehexstring",
  "writeobject",
  "writestring",
  "=equal",
  "==",
  "bytesavailable",
  "flush",
  "flushfile",
  "resetfile",
  "run",
  "stack",

  // Graphics – Path construction
  "newpath",
  "closepath",
  "moveto",
  "rmoveto",
  "lineto",
  "rlineto",
  "curveto",
  "rcurveto",
  "arc",
  "arcn",
  "arcto",

  // Graphics – Painting
  "stroke",
  "fill",
  "eofill",
  "clip",
  "eoclip",

  // Graphics – Transformations
  "translate",
  "scale",
  "rotate",
  "transform",
  "itransform",
  "dtransform",
  "idtransform",
  "matrix",
  "initmatrix",
  "defaultmatrix",
  "currentmatrix",
  "setmatrix",
  "concat",
  "concatmatrix",

  // Graphics – State save/restore
  "gsave",
  "grestore",
  "grestoreall",
  "save",
  "restore",
  "initgraphics",

  // Graphics – Line styles
  "setlinecap",
  "setlinejoin",
  "setlinewidth",
  "setmiterlimit",
  "setdash",
  "currentlinecap",
  "currentlinejoin",
  "currentlinewidth",
  "currentmiterlimit",
  "currentdash",

  // Color (L2+)
  "setgray",
  "currentgray",
  "setrgbcolor",
  "currentrgbcolor",
  "sethsbcolor",
  "currenthsbcolor",
  "setcmykcolor",
  "currentcmykcolor",
  "setcolorspace",
  "currentcolorspace",
  "setcolor",
  "currentcolor",

  // Fonts & Text
  "findfont",
  "scalefont",
  "makefont",
  "setfont",
  "currentfont",
  "definefont",
  "undefinefont",
  "stringwidth",
  "charpath",
  "show",
  "ashow",
  "widthshow",
  "awidthshow",
  "kshow",
  "glyphshow",
  "showpage",

  // Images
  "image",
  "imagemask",
  "colorimage",
  "shfill",

  // Forms & Patterns (L2/L3)
  "execform",
  "makepattern",
  "setpattern",
  "currentpattern",
  "setcolorscreen",
  "setscreen",
  "sethalftone",
  "currenthalftone",
  "sethalftonephase",
  "currenthalftonephase",
  "setcolortransfer",
  "currentcolortransfer",
  "settransfer",
  "currenttransfer",

  // Device & Rendering control
  "setflat",
  "currentflat",
  "setrenderingintent",
  "currentrenderingintent",
  "setoverprint",
  "currentoverprint",
  "setoverprintmode",
  "currentoverprintmode",
  "setblackgeneration",
  "currentblackgeneration",
  "setundercolorremoval",
  "currentundercolorremoval",
  "setucacheparams",
  "currentucacheparams",

  // System & Environment
  "version",
  "revision",
  "product",
  "languagelevel",
  "serialnumber",
  "executive",
  "echo",
  "prompt",
  "type",
  "countexecstack",
  "execstack",
  "stackunderflow",
  "handleerror",
  "errordict",

  // Level 2+ Data filters
  "filter",
  "closefile",
  "read",
  "readhexstring",
  "readline",
  "readstring",
  "write",
  "writehexstring",
  "writestring",

  // Level 3 additions (transparency, compositing, advanced imaging)
  "setcolorspace",
  "setcolor",
  "currentcolorspace",
  "currentcolor",
  "seticcprofile",
  "currenticcprofile",
  "setblendmode",
  "currentblendmode",
  "setsoftmask",
  "currentsoftmask",
  "setopacityalpha",
  "currentopacityalpha",
  "setshapealpha",
  "currentshapealpha"
]);
